INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alecrim','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alho','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('canela','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cheiro-verde','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cominho','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('curry','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gengibre','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('hortelã','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('louro','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mostarda (grão)','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('nos-moscada','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pimenta','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('raiz-forte','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sal','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salsão','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suco de limão','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tomilho','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vinagre','Temperos',0,'a seu gosto');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('acelga','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('agrião','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alface','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alga marinha','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('almeirão','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chicória','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('couve','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('erva-doce','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('escarola','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('espinafre','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('jiló','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maxixe','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mostarda','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('nabo','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pepino','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pimentão','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('rabanete','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('repolho','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('rúcula','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salsão','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('taioba','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tomate','Verduras',0,'consumo livre');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('água','Bebidas',0,'à vontade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('café','Bebidas',0,'à vontade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chá','Bebidas',0,'à vontade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('limonada','Bebidas',0,'à vontade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('abóbora','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('abobrinha','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alcachofra','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('aspargo','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('berinjela','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('beterraba','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('brócolis','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('broto de bambu','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('broto de feijão','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cebola','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cebolinha','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cenoura','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chuchu','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cogumelo','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('couve-flor','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ervilha fresca','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('palmito','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('quiabo','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vagem','Legumes',10,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('abacate','Frutas',11,'1/4 de unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('abacaxi','Frutas',11,'1 rodela pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('abricó','Frutas',11,'2 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ameixa','Frutas',11,'2 unidades pequenas');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('amora','Frutas',11,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('banana-maçã','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('banana-nanica','Frutas',11,'1/2 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('banana-ouro','Frutas',11,'2 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('banana-prata','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caju','Frutas',11,'2 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caqui','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('carambola','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cereja','Frutas',11,'10 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('damasco seco','Frutas',11,'4 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('figo fresco','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('framboesa','Frutas',11,'1/2 copo');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fruta-do-conde','Frutas',11,'1/2 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('goiaba','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('grapefruit','Frutas',11,'1/2 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('jabuticaba','Frutas',11,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('kiwi','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('laranja','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lima-da-pérsia','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maçã','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mamão','Frutas',11,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('manga','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maracujá','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('melancia','Frutas',11,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('melão','Frutas',11,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('morango','Frutas',11,'10 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('nectarina','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('papaia','Frutas',11,'1/4 de unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pera','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pêssego','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pitanga','Frutas',11,'1 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salada de frutas','Frutas',11,'1/2 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tâmara','Frutas',11,'2 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tangerina','Frutas',11,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('uva','Frutas',11,'12 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('uva-passa','Frutas',11,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('manteiga','Gorduras',15,'1 colher (chá) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('margarina','Gorduras',15,'1 colher (chá) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('óleo','Gorduras',15,'1 colher (chá) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('azeite','Gorduras',15,'1 colher (chá) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de leite','Gorduras',15,'1 colher (chá) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme chantili','Gorduras',15,'1 colher (sobremesa) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('arroz','Grãos e Farináceos',20,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('aveia em flocos','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bardana','Grãos e Farináceos',20,'2 pedaços pequenos');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('batata','Grãos e Farináceos',20,'1 unidade média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('batata-doce','Grãos e Farináceos',20,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de milho','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cuscuz','Grãos e Farináceos',20,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ervilha','Grãos e Farináceos',20,'4 colheres(sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('farelo de aveia','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('farelo de trigo','Grãos e Farináceos',20,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('farinha de trigo','Grãos e Farináceos',20,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('farofa','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fava','Grãos e Farináceos',20,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('feijão','Grãos e Farináceos',20,'4 colheres(sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('feijão-branco','Grãos e Farináceos',20,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('flocos de arroz','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('flocos de milho','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fubá','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gergelim','Grãos e Farináceos',20,'1 colher (sobremesa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('germe de trigo','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('grão-de-bico','Grãos e Farináceos',20,'3 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lentilha','Grãos e Farináceos',20,'4 colheres(sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('macarrão cozido','Grãos e Farináceos',20,'1 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maisena','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mandioca','Grãos e Farináceos',20,'1 pedaço pequeno');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mandioquinha','Grãos e Farináceos',20,'3 pedaços pequenos');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('matzá/azimo','Grãos e Farináceos',20,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('milho verde','Grãos e Farináceos',20,'3 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('polenta assada','Grãos e Farináceos',20,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('purê de batata','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('risoto','Grãos e Farináceos',20,'1 1/2 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cereal matinal de milho','Grãos e Farináceos',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('goma para tapioca','Grãos e Farináceos',20,'2 colheres (sopa) rasas');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('trigo-sarraceno','Grãos e Farináceos',20,'1 1/2 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cream-cracker','Pães e biscoitos salgados',20,'3 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('biscoito de água e sal','Pães e biscoitos salgados',20,'3 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('broa de milho','Pães e biscoitos salgados',20,'1/3 de unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('croissant','Pães e biscoitos salgados',20,'1/3 de unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de centeio','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão comum','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de forma','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de glúten','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de hambúrguer','Pães e biscoitos salgados',20,'1/3 de unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de cachorro-quente','Pães e biscoitos salgados',20,'1/3 de unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de leite','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão de queijo','Pães e biscoitos salgados',20,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão francês','Pães e biscoitos salgados',20,'1/2 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão integral','Pães e biscoitos salgados',20,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão italiano','Pães e biscoitos salgados',20,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pão sírio','Pães e biscoitos salgados',20,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('torrada','Pães e biscoitos salgados',20,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('almôndega','Carnes',25,'1 unidade média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('arenque defumado','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('atum em conserva','Carnes',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('aves sem pele','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bacalhau','Carnes',25,'1 pires (café)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cabrito','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('camarão seco','Carnes',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caranguejo','Carnes',25,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('carne de soja','Carnes',25,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('carne magra de vaca','Carnes',25,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('carne moída','Carnes',25,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('carne-seca','Carnes',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('coelho','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cordeiro','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fígado de boi','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('hambúrguer','Carnes',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lagosta','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('língua','Carnes',25,'1 fatia fina');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lingüiça','Carnes',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lombo defumado','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lula','Carnes',25,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('marisco','Carnes',25,'1 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('miolo','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('miúdos','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ostras/mexilhões','Carnes',25,'5 unidades médias');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ovo','Carnes',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ovo de codorna','Carnes',25,'4 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('peito de peru defumado','Carnes',25,'2 fatias finas');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('peixe em conserva','Carnes',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('peixe fresco','Carnes',25,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('peixe salgado','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('polvo','Carnes',25,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('porco','Carnes',25,'1/2 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('presunto','Carnes',25,'1 fatia fina');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('quibe assado','Carnes',25,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('quibe cru','Carnes',25,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('rã','Carnes',25,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('rosbife','Carnes',25,'2 fatias finas');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salmão defumado','Carnes',25,'1 porção pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salsicha','Carnes',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sardinha em óleo','Carnes',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sardinha em tomate','Carnes',25,'3 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sardinha fresca','Carnes',25,'5 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vieira','Carnes',25,'1 pires (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alouette natural','Queijos',25,'1 colher (sopa) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('camembert','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fondue','Queijos',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gorgonzola','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gruyère','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('minas','Queijos',25,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mussarela','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mussarela de búfala','Queijos',25,'1/2 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('parmesão','Queijos',25,'1 colher (sopa) rasa');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('polenguinho','Queijos',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('prato','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('provolone','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tofu','Queijos',25,'1 fatia grande');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('requeijão','Queijos',25,'2 colheres (sobremesa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ricota','Queijos',25,'1 fatia grande');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('roquefort','Queijos',25,'1 fatia pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('coalhada seca','Leite e derivados',42,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de leite','Leite e derivados',42,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('iogurte','Leite e derivados',42,'1 copo = 200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('iogurte desnatado','Leite e derivados',42,'2 copos = 400ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('leite de soja','Leite e derivados',42,'1/2 copo = 100ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('leite integral','Leite e derivados',42,'1 copo = 200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('leite integral em pó','Leite e derivados',42,'1 1/2 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('leite desnatado','Leite e derivados',42,'2 copos = 400ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('amêndoa','Aperitivos e lanches',5,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('amendoim','Aperitivos e lanches',45,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('azeitona','Aperitivos e lanches',5,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('barra de cereais','Aperitivos e lanches',28,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('batata chips','Aperitivos e lanches',118,'80g');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('batata frita','Aperitivos e lanches',110,'porção grande');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('beirute','Aperitivos e lanches',140,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('biscoito de polvilho','Aperitivos e lanches',60,'50g');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('castanha de caju','Aperitivos e lanches',35,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caviar','Aperitivos e lanches',25,'4 colheres (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('croquete','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('coxinha','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('empadinha','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('esfirra','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('folhado','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('hambúrguer','Aperitivos e lanches',72,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('misto-quente','Aperitivos e lanches',90,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('nozes','Aperitivos e lanches',50,'1/2 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pastel','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('patê de berinjela','Aperitivos e lanches',10,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('patê de fígado','Aperitivos e lanches',15,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('patê de galinha','Aperitivos e lanches',10,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pinhão cozido','Aperitivos e lanches',40,'1 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pistache','Aperitivos e lanches',50,'1/2 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('quibe','Aperitivos e lanches',10,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sanduíche tipo americano','Aperitivos e lanches',160,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tapioca','Aperitivos e lanches',90,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('torresmo','Aperitivos e lanches',30,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('torta salgada','Aperitivos e lanches',50,'1 pedaço médio');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tremoço','Aperitivos e lanches',55,'1 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('água de coco','Bebidas normais',10,'200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('batida de frutas','Bebidas normais',60,'100ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caldo de cana','Bebidas normais',45,'200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cerveja ou chope','Bebidas normais',24,'200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gim','Bebidas normais',40,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('licor','Bebidas normais',50,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('refrigerante','Bebidas normais',22,'200ml');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suco de maçã','Bebidas normais',25,'1 caixinha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suco de vegetais','Bebidas normais',15,'1 caixinha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('saquê','Bebidas normais',40,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vermute','Bebidas normais',40,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vinho','Bebidas normais',35,'1 taça');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vodca','Bebidas normais',40,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('uísque','Bebidas normais',40,'1 dose');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bala','Linha diet e light',2,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cappuccino','Linha diet e light',5,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chocolate em pó','Linha diet e light',10,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('frozen yogurt','Linha diet e light',17,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gelatina','Linha diet e light',5,'1 taça');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('geleia','Linha diet e light',3,'1 colher (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('groselha','Linha diet e light',5,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('iogurte','Linha diet e light',18,'1 copo');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pudim','Linha diet e light',20,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('refresco','Linha diet e light',5,'1 copo');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sorvete','Linha diet e light',37,'1 bola');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('picolé','Linha diet e light',12,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('waffle','Linha diet e light',3,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('achocolatados','Doces',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('açúcar','Doces',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('açúcar mascavo','Doces',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('alfajor','Doces',90,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('arroz-doce','Doces',35,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bala','Doces',6,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('biscoito recheado','Doces',30,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bolachinha','Doces',25,'3 unidades');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bolo simples','Doces',50,'1 fatia');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bomba de creme','Doces',140,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('brigadeiro','Doces',30,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('canjica','Doces',45,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chiclete','Doces',6,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('chocolate','Doces',60,'1 tabelete pequeno');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('coberturas','Doces',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cocada','Doces',40,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('coco ralado','Doces',15,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('cookie','Doces',25,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('doce de abóbora','Doces',35,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('doce de leite','Doces',25,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('fios de ovos','Doces',70,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('gelatina','Doces',19,'1 taça');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('goiabada','Doces',20,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('leite de coco','Doces',60,'1/2 copo');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maria-mole','Doces',40,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mel','Doces',17,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('merengue','Doces',60,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('musse de chocolate','Doces',55,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('paçoca','Doces',35,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pamonha','Doces',55,'1 taça');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('panetone','Doces',35,'1 fatia fina');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('picolé com leite','Doces',40,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('picolé de frutas','Doces',20,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pudim','Doces',40,'1 fatia fina');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sonho','Doces',100,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sorvete','Doces',50,'1 bola');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suspiro','Doces',25,'1 unidade pequena');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('torta doce','Doces',55,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('canelone','Massas',20,'1 unidade média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('capelete','Massas',20,'1/2 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('lasanha','Massas',170,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('nhoque','Massas',20,'3 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('panqueca','Massas',70,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('pizza','Massas',70,'1 fatia média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ravioli','Massas',20,'1/2 xícara (chá)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bife à parmegiana','Pratos',135,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('estrogonofe','Pratos',55,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('feijoada','Pratos',25,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('homos','Pratos',30,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('kafta','Pratos',60,'1 espetinho');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sashimi','Pratos',25,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suflê de legumes','Pratos',40,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('suflê de queijo','Pratos',60,'1 porção média');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sushi','Pratos',15,'1 unidade');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('vatapá','Pratos',35,'1 porção');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('bolonhesa','Molhos',17,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('branco','Molhos',17,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('ketchup','Molhos',10,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('inglês','Molhos',7,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('mostarda','Molhos',7,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('maionese','Molhos',40,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('camarão com catupiry','Molhos',50,'2 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('salada de maionese','Molhos',55,'1 colher (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('tabule, sem azeite','Molhos',20,'3 colheres (sopa)');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caldo de carne','Sopas',10,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('caldo de galinha','Sopas',20,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('canja, sem pele','Sopas',30,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('consomê de carne','Sopas',5,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de aspargo','Sopas',30,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de cebola','Sopas',15,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de cogumelo','Sopas',30,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('creme de ervilha','Sopas',35,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sopa de feijão branco','Sopas',35,'1 concha');
INSERT INTO `meuspontos`.`Alimento` (`alim_descricao`, `alim_tipo`, `alim_qtdePontos`, `alim_medida`) VALUES ('sopa de vegetais, enlatada','Sopas',35,'1 concha');
